# Install tree package 

package 'tree' do 

  action :install 

end 

 

# Create the directory if it does not exist 

directory '/testcook/recipes/recipe2' do 

  owner 'root' 

  group 'root' 

  mode '0755' 

  action :create 

end 

 

# Create or update the file 

file '/testcook/recipes/recipe2/myfile2.txt' do 

  content 'Welcome in the second recipe generated by co-pilot' 

  owner 'root' 

  group 'root' 

  mode '0755' 

  action :create 

end 
