name: Chef to Ansible Conversion

on:
  push:
    branches: [ main ]

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create directory
      run: mkdir my_directory

    - name: Checkout other repository
      uses: actions/checkout@v2
      with:
        repository: GargTanya/Chef-ansible
        path: https://github.com/GargTanya/Chef-ansible.git/my_directory

    - name: Setup Python
      uses: actions/setup-python@v5.1.0

    - name: Install Langchain
      run: |
             python -m pip install --upgrade pip
              pip install langchain


    - name: Run conversion script
      run: python convert.py

    - name: Commit and push changes
      run: |
        git config --local user.email "tanyagarg1311@gmail.com"
        git config --local user.name "GargTanya"
        git add .
        git commit -m "Add converted playbook files" -a
        git push
    env:
       GITHUB_TOKEN: ${{ secrets.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 }}
