name: Chef to Ansible Conversion

on:
  push:
    branches: [ main ]

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create directory
      run: mkdir my_directory

    - name: Checkout other repository
      uses: actions/checkout@v2
      with:
        repository: GargTanya/Chef-ansible
        path: https://github.com/GargTanya/Chef-ansible.git/my_directory

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run conversion script
      run: python convert.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add converted playbook files" -a
        git push
