name: Chef to Ansible Conversion

on:
  push:
    branches: [ main ]

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create directory
      run: mkdir -p my_directory

    - name: Checkout other repository
      uses: actions/checkout@v2
      with:
        repository: org/repo
        path: my_directory

    - name: Install dependencies
      run: |
        sudo apt-get install -y python3-pip
        pip3 install -r requirements.txt

    - name: Run conversion script
      run: python3 convert.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add converted playbook files" -a
        git push
